### ISSUE TITLE
Bootstrap 3.3.2 (less/mixins/grid.less)

### ISSUE THREAD

**Issue by Tanyusha** [andreypopp/less2stylus#3]
```
lesscss-percentage(n)
  (n * 100)%
container-fixed(gutter=grid-gutter-width)
  margin-right auto
  margin-left auto
  padding-left (gutter / 2)
  padding-right (gutter / 2)

C:\your-project\node_modules\less2stylus\index.js:126
    throw new Error('not implemented');
          ^
Error: not implemented
    at Object.baseVisitor.visitExtend (C:\your-project\node_modules\less2stylus\index.js:126:11)
    at Object.tree.visitor.visit (C:\your-project\node_modules\less2stylus\node_modules\less\lib\less\visitor.js:23:32)
    at renderTree (C:\your-project\node_modules\less2stylus\index.js:44:33)
    at Object.defineVisitor.visitMixinDefinition (C:\your-project\node_modules\less2stylus\index.js:419:7)
    at Object.tree.visitor.visit (C:\your-project\node_modules\less2stylus\node_modules\less\lib\less\visitor.js:23:32)
    at Object.tree.visitor.visitArray (C:\your-project\node_modules\less2stylus\node_modules\less\lib\less\visitor.js:40:34)
    at Object.tree.visitor.visit (C:\your-project\node_modules\less2stylus\node_modules\less\lib\less\visitor.js:11:29)
    at Object.tree.Ruleset.accept (C:\your-project\node_modules\less2stylus\node_modules\less\lib\less\tree\ruleset.js:13:30)
    at Object.tree.visitor.visit (C:\your-project\node_modules\less2stylus\node_modules\less\lib\less\visitor.js:29:22)
    at renderTree (C:\your-project\node_modules\less2stylus\index.js:44:33)
```

**Comment by deedw** [comment]
Take a look at the fork at https://github.com/coursera/less2stylus

They seem to have added functionality that allows conversion of all the Bootstrap less files - although some of the generated files throw errors when run through stylus, so some tweaking may be required.
